name: Lint

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ESLint
        run: npm ci && ls node_modules/.bin
        continue-on-error: true
      - name: Run ESLint
        uses: stefanoeb/eslint-action@1.0.2
