name: Lint

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ESLint
        run: npm ci && ls node_modules/.bin
        if: succeeded() || failed()
      - name: Run ESLint
        if: always()
        uses: stefanoeb/eslint-action@1.0.2
