name: Lint

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - run: npm install --only=dev
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
